export type AllDocsPages =
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenNightly Builds.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyendeclaration-filesBy Example.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyendeclaration-filesConsumption.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyendeclaration-filesDeep Dive.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyendeclaration-filesDo's and Don'ts.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyendeclaration-filesIntroduction.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyendeclaration-filesLibrary Structures.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyendeclaration-filesPublishing.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyendeclaration-filesTemplates.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyendeclaration-files\templatesglobal-modifying-module.d.ts.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyendeclaration-files\templatesglobal-plugin.d.ts.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyendeclaration-files\templatesglobal.d.ts.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyendeclaration-files\templatesmodule-class.d.ts.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyendeclaration-files\templatesmodule-function.d.ts.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyendeclaration-files\templatesmodule-plugin.d.ts.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyendeclaration-files\templatesmodule.d.ts.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenget-startedTS for Functional Programmers.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenget-startedTS for JS Programmers.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenget-startedTS for OOPers.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenget-startedTS for the New Programmer.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v1Basic Types.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v1Classes.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v1Functions.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v1Generics.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v1Interfaces.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v1Literal Types.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v1Unions and Intersections.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2Basics.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2Classes.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2Everyday Types.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2Modules.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2More on Functions.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2Narrowing.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2Object Types.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2The Handbook.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2Type Declarations.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2Understanding Errors.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2Type ManipulationConditional Types.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2Type ManipulationGenerics.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2Type ManipulationIndexed Access Types.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2Type ManipulationKeyof Type Operator.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2Type ManipulationMapped Types.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2Type ManipulationTemplate Literal Types.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2Type ManipulationTypeof Type Operator.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenhandbook-v2Type Manipulation_Creating Types from Types.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenjavascriptCreating DTS files From JS.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenjavascriptIntro to JS with TS.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenjavascriptJSDoc Reference.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenjavascriptType Checking JavaScript Files.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenproject-configCompiler Options in MSBuild.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenproject-configCompiler Options.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenproject-configConfiguring Watch.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenproject-configIntegrating with Build Tools.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenproject-configProject References.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyenproject-config\tsconfig.json.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceAdvanced Types.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceDeclaration Merging.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceDecorators.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceEnums.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceIterators and Generators.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceJSX.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceMixins.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceModule Resolution.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceModules.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceNamespaces and Modules.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceNamespaces.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceSymbols.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceTriple-Slash Directives.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceType Compatibility.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceType Inference.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceUtility Types.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\referenceVariable Declarations.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesOverview.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 1.1.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 1.3.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 1.4.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 1.5.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 1.6.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 1.7.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 1.8.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 2.0.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 2.1.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 2.2.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 2.3.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 2.4.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 2.5.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 2.6.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 2.7.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 2.8.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 2.9.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 3.0.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 3.1.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 3.2.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 3.3.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 3.4.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 3.5.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 3.6.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 3.7.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 3.8.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 3.9.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 4.0.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 4.1.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 4.2.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 4.3.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 4.4.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\release-notesTypeScript 4.5.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\tutorialsAngular.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\tutorialsASP.NET Core.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\tutorialsBabel with TypeScript.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\tutorialsDOM Manipulation.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\tutorialsGulp.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\tutorialsMigrating from JavaScript.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\tutorialsReact.md"
  | "C:Users\tomasOneDriveDocumentos\typescript-translateTypeScript-websitepackagesdocumentationcopyen\tutorialsTypeScript Tooling in 5 minutes.md";
